services: 
  frontend:
    build: frontend/
    volumes:
      - type: bind
        source: /var/lib/portfolio/portfolio.db
        target: /app/db/portfolio.db
      - type: bind
        source: /var/lib/portfolio/info/
        target: /app/info/
      - type: bind
        source: /var/lib/portfolio/md
        target: /app/md
      - type: bind
        source: /var/lib/portfolio/message
        target: /app/message
    ports:
    - "1375:1375"
  api:
    build: api/
    volumes:
      - type: bind
        source: /var/lib/portfolio/portfolio.db
        target: /app/db/portfolio.db
    ports:
      - "5731:5731"
